# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-12 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170702_1725'),
        ('manager', '0008_auto_20170707_1007'),
    ]

    operations = [
    ]
